select * from customer limit 10


-- what is the total revenue generated by male vs female customer
select gender, sum(purchase_amount) as revenue
from customer 
group by gender

-- which customer used a discount but still spent more than the avergae purchcase amount
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes'
and purchase_amount >= (select avg(purchase_amount) from customer)

-- which are the top 5 products with the highest average review rating
select item_purchased as product, round(avg(review_rating::numeric),3) as rating
from customer
group by item_purchased
order by rating desc
limit 5

-- compare the average purchase amount between standard and express shipping
select shipping_type, round(avg(purchase_amount),2)
from customer
where shipping_type in ('Express','Standard')
group by shipping_type

-- do subscribed customers spend more? compare average spend and total revenue between subscribers and non-subscribers
select subscription_status,
count(customer_id)as total_customer,
round(avg(purchase_amount),2) as average_spend,
sum(purchase_amount)
from customer
group by subscription_status

-- which 5 products have the highest percentage of purchases with discounts applied
select item_purchased as product, 
100*sum(case when discount_applied = 'Yes' then 1 else 0 end)/count(discount_applied) as percentage_dis_applied
from customer
group by product
order by percentage_dis_applied desc
limit 5

-- segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment
with customer_type as (
select customer_id, previous_purchases,
case
	when previous_purchases = 1 then 'New'
	when previous_purchases between 2 and 10 then 'Returning'
	else 'Loyal'
	end as customer_segment
from customer
)
select customer_segment, count(*) as "Number of customers"
from customer_type
group by customer_segment

-- what are the top 3 most purchased products within each category
with ranked_product as(
select category, item_purchased, count(customer_id) as total_orders,
row_number() over(partition by category order by count(customer_id) desc) as rank
from customer
group by category, item_purchased
)
select rank, category, item_purchased, total_orders
from ranked_product
where rank <=3

-- are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe
select subscription_status, count(customer_id) as "repeat buyers"
from customer
where previous_purchases > 5
group by subscription_status

-- what is the revenue contribution of each age group
select age_group, sum(purchase_amount) as revenue
from customer 
group by age_group
order by revenue desc

